apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
    name: Python-app
    description: A Python Library
    annotations:
        backstage.io/techdocs-ref: dir:.
        github.com/project-slug: sumit-ct-02/idp-ingestion-example
  
spec:
    type: service
    lifecycle: production
    owner: backstage-catalog-group 
  
